### ISSUE TITLE
某新聞社様 CVO HA環境においてCVOアップグレード中にアプリ停止(CASE#2009640568)

### ISSUE THREAD

**Issue by kawakawa1A** [NetAppDocs/bluexp-cloud-volumes-ontap.ja-jp#1]
### Page URL

https://docs.netapp.com/ja-jp/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html

### Page title

Cloud Volumes ONTAP ソフトウェアをアップグレードします

### Summary

以下CVOマニュアルの記載について変更をリクエストします。
https://docs.netapp.com/ja-jp/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#%E3%82%A2%E3%83%83%E3%83%97%E3%82%B0%E3%83%AC%E3%83%BC%E3%83%89%E3%82%92%E6%BA%96%E5%82%99

「ダウンタイムを計画」
「HA ペアのアップグレードは無停止で、 I/O が中断されません。無停止アップグレードでは、各ノードが連携してアップグレードされ、クライアントへの I/O の提供が継続されます。」

という記載がございます。

某新聞社様 CVO HA環境においてCVOアップグレードをおこなったときに
アプリケーション停止が発生しました。
本記載を元に、現場からは「なぜI/Oの提供が継続されると記載されているにもかかわらず、
アプリケーションが停止したのか」とエスカレーションされています。

ONTAPマニュアルについては以下記載があり、今回の事象に該当すると考えます。
https://docs.netapp.com/ja-jp/ontap/upgrade/concept_considerations_for_session_oriented_protocols.html
「セッション指向プロトコルに関する考慮事項」
「アプリケーション（ Oracle や Exchange など）影響はアプリケーションによって異なります。タイムアウトベースのアプリケーションでは、タイムアウトの値を ONTAP のリブート時間よりも長く設定することで、悪影響を最小限に抑えることができます。」

CVOマニュアルの記載は楽観的であり、実際にはONTAPマニュアルにある注意喚起する方が
CVOとしても同じONTAPとしての仕様記述と考えます。

★★リクエストとしては、CVOマニュアルの該当記載を削除して、
ONTAPマニュアルの該当記述をCVO側にも記載していただきたいです。★★

某新聞社様の現場には、ONTAPマニュアルの該当記述を仕様として
CVOマニュアルを修正する旨で回答したいと考えます。

以上、宜しくお願いいたします。

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
この度は貴重なフィードバックをいただき、ありがとうございました。ご指摘の内容について、以下のように修正しましたので、ご確認ください。
Thank you for your valuable feedback. The content has been updated accordingly. Could you please confirm?
更新後の内容が表示されない場合は、お手数ですが、ブラウザーの設定画面でキャッシュのクリアをお試しください。
Please try clearing your browser cache in case the updates aren’t reflected:

English: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#prepare-to-upgrade

![image](https://github.com/NetAppDocs/bluexp-cloud-volumes-ontap.ja-jp/assets/18287750/789dbf4b-204a-45d4-92a0-ebb62ae5e6da)

Japanese: https://docs.netapp.com/ja-jp/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#%E3%82%A2%E3%83%83%E3%83%97%E3%82%B0%E3%83%AC%E3%83%BC%E3%83%89%E3%82%92%E6%BA%96%E5%82%99

![image](https://github.com/NetAppDocs/bluexp-cloud-volumes-ontap.ja-jp/assets/18287750/42e8e70d-9196-481c-b968-d968ec0efbb1)

Regards,
Ben Cammett

**Comment by kawakawa1A** [comment]
To: Ben Cammett様
Fm:川田

お世話になっております。

マニュアル修正対応のご対応誠にありがとうございました。
弊社の品質保証部門にも確認しまして記載修正いただいた内容で監査クリアいたしました。

エスカレーションされた現場へも修正された内容を伝えてクローズを図ってまいります。

以上、御礼メールまで。

**Comment by netapp-gudugunti** [comment]
Thanks! for confirming the fix, @kawakawa1A.
Closing the issue.
